import imageMap from "@/lib/data/ingredient-image-map.json";

// Canonical Ingredient.name -> slug of a file in public/images/ingredients/.
// Generated by `npm run thumbs:match` then reviewed by hand; imported as a
// build-time constant so lookups need no query and can never 404 at runtime.
// Ingredients with no art simply aren't keys here — callers fall back.
const MAP = imageMap as Record<string, string>;

const COMBINING_MARKS = /[̀-ͯ]/g;

export function normalizeIngredientName(name: string): string {
  return name.normalize("NFD").replace(COMBINING_MARKS, "").toLowerCase().trim();
}

const NORMALIZED: Record<string, string> = Object.fromEntries(
  Object.entries(MAP).map(([name, slug]) => [normalizeIngredientName(name), slug])
);

export function getIngredientImage(name: string): string | null {
  const slug = NORMALIZED[normalizeIngredientName(name)];
  return slug ? `/images/ingredients/${slug}.webp` : null;
}
